### ISSUE TITLE
fallback function, should we make it do something

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-bridge#3]
The vault I assume has a fallback function, but what happens if someone sends ETH to the mainnet bridge contract now would be that money goes there and thats it... no coins are created on the other side of the bridge.

Should we set it as a default donation to the DAC?

My main thinking here is that i really don't want to have some eth in this contract that doesnt have a corresponding token on the foreign side

**Comment by perissology** [comment]
there is not fallback function. only the 4 donate functions are payable
