### ISSUE TITLE
Change gas price option in sending transactions based on EIP 1559 update

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-bridge#32]
Bridge still uses legacy `gasPrice` option in sending transactions and it doesn't benefit from what has been implemented as EIP 1559. 
By setting the old `gasPrice` in sending transaction we deprive us of refund

![image](https://user-images.githubusercontent.com/5684607/131073666-cead317d-26f0-4a49-a736-e6bd21a0bea2.png)

I suggest setting a high price (gas price service + 100 Gwei) as `Max Fee` and very little price (1 or 2 Gwei) as `Max Priority Fee`

**Comment by GriffGreen** [comment]
I agree! @aminlatifi great call. 

Playing the gas markets lately I would only add 50 gwei ontop of the base price for the max fee and 2.1 for the priority fee... we might have txs stuck for a little bit, but still the gas cost is so expensive... its prob ok to have a few delays when an NFT drop happens.. it will delay us for an hour but... thats prob better than paying an extra $20

**Comment by aminlatifi** [comment]
It's not possible to broadcast a transaction message with gas price less than block base price! So the solution would be hold on sending the transaction till the max price we can afford become more than the block base price!
